version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=123t456'
      - 'POSTGRES_DB=rest_app_db'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080